[package]
name = "tz"
description = "Library for parsing zoneinfo files"

authors = ["Ben S <ogham@bsago.me>"]
documentation = "http://datetime.rustdocs.org/tz/"
homepage = "https://github.com/ogham/rust-tz"
license = "MIT"
version = "0.2.0"

[lib]
name = "tz"

[dependencies]
byteorder = "*"
